# Generated by Django 5.2.1 on 2026-01-13 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sucursal_dominiosucursal'),
        ('inventario', '0002_alter_producto_options_producto_codigo_barras_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de envío'), ('EN_TRANSITO', 'En tránsito'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de recepción')),
                ('numero_guia', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Número de guía')),
                ('observaciones_envio', models.TextField(blank=True, null=True, verbose_name='Observaciones del envío')),
                ('observaciones_recepcion', models.TextField(blank=True, null=True, verbose_name='Observaciones de la recepción')),
                ('sucursal_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recibidas', to='core.sucursal', verbose_name='Sucursal Destino')),
                ('sucursal_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to='core.sucursal', verbose_name='Sucursal Origen')),
                ('usuario_envia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que envía')),
                ('usuario_recibe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que recibe')),
            ],
            options={
                'verbose_name': 'Transferencia de Inventario',
                'verbose_name_plural': 'Transferencias de Inventario',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='DetalleTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_codigo', models.CharField(max_length=50, verbose_name='Código del producto')),
                ('producto_nombre', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('cantidad_enviada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad enviada')),
                ('cantidad_recibida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad recibida')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.transferenciainventario', verbose_name='Transferencia')),
            ],
            options={
                'verbose_name': 'Detalle de Transferencia',
                'verbose_name_plural': 'Detalles de Transferencia',
                'ordering': ['producto_nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='transferenciainventario',
            index=models.Index(fields=['sucursal_origen', 'estado'], name='inventario__sucursa_28dcd6_idx'),
        ),
        migrations.AddIndex(
            model_name='transferenciainventario',
            index=models.Index(fields=['sucursal_destino', 'estado'], name='inventario__sucursa_737469_idx'),
        ),
        migrations.AddIndex(
            model_name='transferenciainventario',
            index=models.Index(fields=['numero_guia'], name='inventario__numero__859968_idx'),
        ),
    ]
