# Generated by Django 5.2.1 on 2026-02-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen 2'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen 3'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Principal'),
        ),
    ]
