# Generated by Django 5.2.1 on 2026-03-17 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_producto_imagen_2_producto_imagen_3_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproducto',
            options={'verbose_name': 'CategorÃ\xada de Producto', 'verbose_name_plural': 'CategorÃ\xadas de Productos'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_ultima_compra',
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='stock_anterior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='stock_nuevo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='detalletransferencia',
            name='producto_codigo',
            field=models.CharField(max_length=50, verbose_name='CÃ³digo del producto'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='barcodes/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_unico',
            field=models.CharField(max_length=50, unique=True, verbose_name='CÃ³digo Ãšnico'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='DescripciÃ³n'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='incluye_iva',
            field=models.BooleanField(default=True, verbose_name='Incluye IVA'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock Actual'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock MÃ\xadnimo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ubicacion_almacen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UbicaciÃ³n en AlmacÃ©n'),
        ),
        migrations.AlterField(
            model_name='transferenciainventario',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de envÃ\xado'), ('EN_TRANSITO', 'En trÃ¡nsito'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='transferenciainventario',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envÃ\xado'),
        ),
        migrations.AlterField(
            model_name='transferenciainventario',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de recepciÃ³n'),
        ),
        migrations.AlterField(
            model_name='transferenciainventario',
            name='numero_guia',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='NÃºmero de guÃ\xada'),
        ),
        migrations.AlterField(
            model_name='transferenciainventario',
            name='observaciones_envio',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones del envÃ\xado'),
        ),
        migrations.AlterField(
            model_name='transferenciainventario',
            name='observaciones_recepcion',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones de la recepciÃ³n'),
        ),
        migrations.AlterField(
            model_name='transferenciainventario',
            name='usuario_envia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que envÃ\xada'),
        ),
    ]
