# Generated by Django 6.0.1 on 2026-04-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_categoriaproducto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_editable',
            field=models.BooleanField(default=False, verbose_name='Es Editable (Nombre/Precio)'),
        ),
    ]
