# Generated by Django 5.2.1 on 2026-08-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_producto_es_editable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código que ingresará el taller o cliente (ej: TALLER5, MECANICO10)', max_length=50, unique=True, verbose_name='Código Promocional')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje Descuento (%)')),
                ('precio_minimo_aplicable', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Mínimo de Producto ($)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Código Promocional',
                'verbose_name_plural': 'Códigos Promocionales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_descuento_global', models.DecimalField(decimal_places=2, default=0.0, help_text='Ejemplo: 5.00 para aplicar 5% de descuento en la tienda', max_digits=5, verbose_name='Porcentaje Descuento Global (%)')),
                ('precio_minimo_descuento', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio a partir del cual aplica el descuento (ej: 2.00 para no descontar ítems como pernos)', max_digits=10, verbose_name='Precio Mínimo de Producto para Descuento ($)')),
                ('descuento_activo', models.BooleanField(default=False, verbose_name='Descuento Global Activo en Tienda')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Tienda Virtual',
                'verbose_name_plural': 'Configuración de Tienda Virtual',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='es_destacado',
            field=models.BooleanField(default=False, verbose_name='Producto Estrella / Destacado Web'),
        ),
    ]
