# Generated by Django 5.2.1 on 2026-08-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_codigopromocional_configuraciontienda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento_especial_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento personalizado individual para este producto (ej: 20.00)', max_digits=5, verbose_name='Descuento Especial Web (%)'),
        ),
    ]
