# Generated by Django 5.2.1 on 2026-08-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_producto_descuento_especial_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontienda',
            name='api_key_secret',
            field=models.CharField(default='vpm_live_secret_key_984102983719827398127398', help_text='Token de seguridad para autorizar a la tienda web', max_length=120, verbose_name='Clave Secreta de API Web (Token)'),
        ),
    ]
