# Generated by Django 5.2.1 on 2026-08-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_configuraciontienda_api_key_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descuento_especial_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Descuento personalizado individual para este producto (ej: 20.00)', max_digits=5, null=True, verbose_name='Descuento Especial Web (%)'),
        ),
    ]
