# Generated by Django 5.2.1 on 2026-08-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_producto_descuento_especial_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontienda',
            name='groq_api_key',
            field=models.CharField(blank=True, help_text='Clave de API de Groq AI para digitalizar facturas y fotos con IA (ej: gsk_...)', max_length=255, null=True, verbose_name='Clave de API Groq (Visión IA)'),
        ),
    ]
