# Generated by Django 5.2.1 on 2026-08-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_configuraciontienda_groq_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontienda',
            name='resend_api_key',
            field=models.CharField(blank=True, help_text='Clave de API de Resend para el envío de facturas por correo electrónico (ej: re_...)', max_length=255, null=True, verbose_name='Clave de API Resend (Emails)'),
        ),
    ]
