# Generated by Django 5.2.1 on 2026-01-13 17:54

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('codigo', models.CharField(help_text='Código único de la sucursal (ej: QUITO, CAYAMBE)', max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la sucursal')),
                ('nombre_corto', models.CharField(help_text='Nombre corto para mostrar en reportes y pantallas', max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ruc', models.CharField(blank=True, help_text='RUC de la sucursal si aplica', max_length=13, null=True)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, null=True)),
                ('es_principal', models.BooleanField(default=False, help_text='Marca esta sucursal como principal/matriz')),
                ('activa', models.BooleanField(default=True)),
                ('prefijo_facturas', models.CharField(blank=True, help_text='Prefijo para numeración de facturas (ej: 001)', max_length=5, null=True)),
                ('prefijo_ordenes', models.CharField(blank=True, help_text='Prefijo para numeración de órdenes (ej: OT-A)', max_length=5, null=True)),
                ('fecha_apertura', models.DateField()),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['-es_principal', 'nombre'],
                'indexes': [models.Index(fields=['codigo'], name='core_sucurs_codigo_41d432_idx'), models.Index(fields=['activa'], name='core_sucurs_activa_9b3cc1_idx'), models.Index(fields=['es_principal'], name='core_sucurs_es_prin_1ee6ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='DominioSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Dominio de Sucursal',
                'verbose_name_plural': 'Dominios de Sucursales',
            },
        ),
    ]
