# Generated by Django 5.2.1 on 2026-04-16 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sucursal_dominiosucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominiosucursal',
            name='domain',
            field=models.CharField(max_length=253, unique=True),
        ),
        migrations.AlterField(
            model_name='dominiosucursal',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dominiosucursal',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dominios', to='core.sucursal'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='schema_name',
            field=models.CharField(default='public', max_length=63, unique=True),
        ),
    ]
