# Generated by Django 5.2.1 on 2026-05-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dominiosucursal_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosistema',
            name='valor',
            field=models.TextField(),
        ),
    ]
