# Generated by Django 5.2.1 on 2025-06-01 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_categoriaservicio_especialidadtecnica_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='es_servicio',
            field=models.BooleanField(default=False, help_text='Indica si este detalle es un servicio (sin IVA)'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, help_text='Tipo de servicio del taller', null=True, on_delete=django.db.models.deletion.PROTECT, to='taller.tiposervicio'),
        ),
        migrations.AddField(
            model_name='venta',
            name='orden_trabajo',
            field=models.ForeignKey(blank=True, help_text='Orden de trabajo asociada a esta venta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='taller.ordentrabajo'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='tecnico',
            field=models.ForeignKey(blank=True, help_text='Técnico que realizó el servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller.tecnico'),
        ),
    ]
