# Generated by Django 5.2.1 on 2025-06-08 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0004_remove_serviciotaller_moto_and_more'),
        ('ventas', '0002_detalleventa_es_servicio_detalleventa_tipo_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta_antiguos', to='taller.tiposervicio'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, help_text='Tipo de servicio del taller', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='taller.tiposervicio'),
        ),
    ]
