# Generated by Django 5.2.1 on 2026-03-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_detalleventa_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='nombre_personalizado',
            field=models.CharField(blank=True, help_text='Nombre para items manuales o genéricos', max_length=200, null=True),
        ),
    ]
