# Generated by Django 5.2.1 on 2026-03-21 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_categoriaproducto_options_and_more'),
        ('taller', '0009_tecnico_fecha_nacimiento'),
        ('ventas', '0004_detalleventa_nombre_personalizado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='total_ingresos_extra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Dinero extra cobrado por cambios a mayor valor', max_digits=10),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='total_reembolsos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Dinero devuelto a clientes', max_digits=10),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='ventas_netas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ventas + Ingresos Extras - Reembolsos', max_digits=10),
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('total_devuelto', models.DecimalField(decimal_places=2, default=0, help_text='Total de productos devueltos por el cliente', max_digits=10)),
                ('total_nuevo', models.DecimalField(decimal_places=2, default=0, help_text='Total de productos nuevos entregados al cliente', max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, help_text='Si es < 0, se reembolsa dinero. Si es > 0, el cliente paga más.', max_digits=10)),
                ('estado', models.CharField(choices=[('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada')], default='COMPLETADA', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEVUELTO', 'Producto Devuelto (Entra a Stock)'), ('NUEVO', 'Producto Nuevo (Sale de Stock)')], max_length=10)),
                ('nombre_personalizado', models.CharField(blank=True, help_text='Nombre para items manuales o genéricos', max_length=200, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('tipo_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taller.tiposervicio')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.devolucion')),
            ],
            options={
                'verbose_name': 'Detalle de Devolución',
                'verbose_name_plural': 'Detalles de Devolución',
            },
        ),
    ]
