# Generated by Django 5.2.1 on 2026-03-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_cierrecaja_total_ingresos_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento aplicado', max_digits=5),
        ),
    ]
