# Generated by Django 5.2.1 on 2026-04-19 07:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0006_detalleventa_descuento_porcentaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='sri/certificados/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['p12'])])),
                ('password_encrypted', models.CharField(max_length=500, verbose_name='Password (Encriptado)')),
                ('nombre_titular', models.CharField(blank=True, max_length=300, null=True)),
                ('ruc_titular', models.CharField(blank=True, max_length=13, null=True)),
                ('emisor', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Certificado Digital',
                'verbose_name_plural': 'Certificados Digitales',
            },
        ),
        migrations.CreateModel(
            name='SRIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.IntegerField(choices=[(1, 'Pruebas'), (2, 'Producción')], default=1)),
                ('tipo_emision', models.IntegerField(choices=[(1, 'Emisión Normal')], default=1)),
                ('ruc', models.CharField(help_text='RUC de la empresa (13 dígitos)', max_length=13)),
                ('razon_social', models.CharField(max_length=300)),
                ('nombre_comercial', models.CharField(blank=True, max_length=300, null=True)),
                ('direccion_matriz', models.TextField()),
                ('obligado_contabilidad', models.BooleanField(default=True)),
                ('contribuyente_especial', models.CharField(blank=True, max_length=20, null=True)),
                ('agente_retencion', models.CharField(blank=True, max_length=20, null=True)),
                ('regimen_microempresas', models.BooleanField(default=False)),
                ('regimen_rimpe', models.BooleanField(default=False)),
                ('wsdl_recepcion_pruebas', models.URLField(default='https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl', help_text='URL WSDL Recepción (Pruebas)')),
                ('wsdl_autorizacion_pruebas', models.URLField(default='https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl', help_text='URL WSDL Autorización (Pruebas)')),
                ('wsdl_recepcion_produccion', models.URLField(default='https://cel.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl', help_text='URL WSDL Recepción (Producción)')),
                ('wsdl_autorizacion_produccion', models.URLField(default='https://cel.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl', help_text='URL WSDL Autorización (Producción)')),
            ],
            options={
                'verbose_name': 'Configuración SRI',
                'verbose_name_plural': 'Configuraciones SRI',
            },
        ),
        migrations.CreateModel(
            name='PuntoEmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.CharField(help_text='Ej: 001', max_length=3)),
                ('punto_emision', models.CharField(help_text='Ej: 001', max_length=3)),
                ('direccion_establecimiento', models.TextField()),
                ('ultimo_secuencial', models.IntegerField(default=0, help_text='El próximo comprobante será este número + 1')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Punto de Emisión',
                'verbose_name_plural': 'Puntos de Emisión',
                'unique_together': {('establecimiento', 'punto_emision')},
            },
        ),
        migrations.CreateModel(
            name='ComprobanteElectronico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_comprobante', models.CharField(default='01', help_text='01=Factura, 04=Nota de Crédito, etc.', max_length=2)),
                ('clave_acceso', models.CharField(blank=True, max_length=49, null=True, unique=True)),
                ('numero_autorizacion', models.CharField(blank=True, max_length=49, null=True)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('CREADO', 'Creado (Pendiente Firma)'), ('FIRMADO', 'Firmado (Pendiente Envío)'), ('RECIBIDO', 'Recibido por SRI'), ('DEVUELTO', 'Devuelto por SRI (Error)'), ('AUTORIZADO', 'Autorizado'), ('RECHAZADO', 'Rechazado'), ('ERROR', 'Error Interno')], default='CREADO', max_length=20)),
                ('ambiente', models.IntegerField(choices=[(1, 'Pruebas'), (2, 'Producción')], default=1)),
                ('xml_generado', models.TextField(blank=True, null=True)),
                ('xml_firmado', models.TextField(blank=True, null=True)),
                ('xml_autorizado', models.TextField(blank=True, null=True)),
                ('pdf_ride', models.FileField(blank=True, null=True, upload_to='sri/rides/')),
                ('mensajes_error', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante_electronico', to='ventas.venta')),
                ('punto_emision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='electronic_invoicing.puntoemision')),
            ],
            options={
                'verbose_name': 'Comprobante Electrónico',
                'verbose_name_plural': 'Comprobantes Electrónicos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
