# Generated by Django 5.2.1 on 2026-04-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteelectronico',
            name='email_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comprobanteelectronico',
            name='email_mensaje',
            field=models.TextField(blank=True, null=True),
        ),
    ]
