# Generated by Django 5.2.1 on 2026-01-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0002_rol_permisos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.AddField(
            model_name='usuario',
            name='permisos',
            field=models.ManyToManyField(blank=True, related_name='usuarios_con_permiso', to='auth.permission', verbose_name='permisos'),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
