# Generated by Django 5.2.1 on 2026-01-13 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sucursal_dominiosucursal'),
        ('usuarios', '0004_alter_usuario_options_remove_usuario_permisos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='puede_ver_todas_sucursales',
            field=models.BooleanField(default=False, help_text='Permite al usuario acceder a todas las sucursales (solo para administradores generales)', verbose_name='Puede ver todas las sucursales'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal a la que pertenece el usuario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.sucursal', verbose_name='Sucursal'),
        ),
    ]
