# Generated by Django 5.2.1 on 2025-06-15 06:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taller', '0005_delete_serviciotaller'),
        ('ventas', '0003_alter_detalleventa_servicio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Movimiento',
                'verbose_name_plural': 'Tipos de Movimientos',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ResumenMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_ventas_productos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_ventas_servicios', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cantidad_ventas', models.IntegerField(default=0)),
                ('cantidad_gastos', models.IntegerField(default=0)),
                ('dias_operacion', models.IntegerField(default=0)),
                ('promedio_venta_dia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('promedio_gasto_dia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('utilidad_bruta', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('margen_utilidad', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_generacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resumen Mensual',
                'verbose_name_plural': 'Resúmenes Mensuales',
                'ordering': ['-año', '-mes'],
                'unique_together': {('año', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='CierreDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('REVISADO', 'Revisado')], default='ABIERTO', max_length=10)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ventas_productos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ventas_servicios', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_iva_cobrado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cantidad_ventas', models.IntegerField(default=0)),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cantidad_gastos', models.IntegerField(default=0)),
                ('efectivo_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tarjeta_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transferencia_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credito_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('efectivo_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('diferencia_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_egresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('observaciones_diferencias', models.TextField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('usuario_cierre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('usuario_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre Diario',
                'verbose_name_plural': 'Cierres Diarios',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fecha'], name='reportes_ci_fecha_a96d60_idx'), models.Index(fields=['estado'], name='reportes_ci_estado_244b21_idx')],
            },
        ),
        migrations.CreateModel(
            name='GastoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('categoria', models.CharField(choices=[('OPERATIVO', 'Gasto Operativo'), ('ADMINISTRATIVO', 'Gasto Administrativo'), ('MANTENIMIENTO', 'Mantenimiento'), ('SERVICIOS_PUBLICOS', 'Servicios Públicos'), ('NOMINA', 'Nómina'), ('IMPUESTOS', 'Impuestos'), ('MARKETING', 'Marketing'), ('OTROS', 'Otros')], max_length=20)),
                ('concepto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True)),
                ('archivo_factura', models.FileField(blank=True, null=True, upload_to='facturas_gastos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto Diario',
                'verbose_name_plural': 'Gastos Diarios',
                'ordering': ['-fecha', '-fecha_creacion'],
                'indexes': [models.Index(fields=['fecha'], name='reportes_ga_fecha_d19219_idx'), models.Index(fields=['categoria'], name='reportes_ga_categor_517b7f_idx'), models.Index(fields=['aprobado'], name='reportes_ga_aprobad_a192a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('concepto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('es_ingreso', models.BooleanField()),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('CREDITO', 'Crédito')], default='EFECTIVO', max_length=20)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('archivo_soporte', models.FileField(blank=True, null=True, upload_to='soportes_caja/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('orden_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taller.ordentrabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
                ('tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reportes.tipomovimiento')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha', '-hora'],
                'indexes': [models.Index(fields=['fecha'], name='reportes_mo_fecha_fbdd7a_idx'), models.Index(fields=['es_ingreso'], name='reportes_mo_es_ingr_912290_idx'), models.Index(fields=['tipo_movimiento'], name='reportes_mo_tipo_mo_20e6a5_idx')],
            },
        ),
    ]
