# Generated by Django 5.2.1 on 2026-02-20 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesgloseBilletes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BILLETE', 'Billete'), ('MONEDA', 'Moneda')], max_length=10)),
                ('denominacion', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Desglose de Billetes',
                'verbose_name_plural': 'Desglose de Billetes',
                'ordering': ['-denominacion'],
            },
        ),
        migrations.AlterModelOptions(
            name='gastodiario',
            options={'ordering': ['-fecha', '-fecha_creacion'], 'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
        migrations.RemoveIndex(
            model_name='movimientocaja',
            name='reportes_mo_tipo_mo_20e6a5_idx',
        ),
        migrations.RenameField(
            model_name='cierrediario',
            old_name='total_gastos',
            new_name='total_gastos_dia',
        ),
        migrations.RemoveField(
            model_name='cierrediario',
            name='cantidad_gastos',
        ),
        migrations.AddField(
            model_name='cierrediario',
            name='total_ordenes_taller',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cierrediario',
            name='total_ventas_online',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='resumenmensual',
            name='total_ordenes_taller',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='resumenmensual',
            name='total_ventas_online',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cierrediario',
            name='usuario_cierre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='desglosebilletes',
            name='cierre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desglose_billetes', to='reportes.cierrediario'),
        ),
    ]
