# Generated by Django 5.2.1 on 2026-03-19 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_desglosebilletes_alter_gastodiario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de Gasto',
                'verbose_name_plural': 'Categorías de Gastos',
                'ordering': ['nombre'],
            },
        ),
        migrations.RenameIndex(
            model_name='gastodiario',
            new_name='reportes_ga_categor_ae8fd3_idx',
            old_name='reportes_ga_categor_517b7f_idx',
        ),
        migrations.AlterField(
            model_name='gastodiario',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reportes.categoriagasto'),
        ),
    ]
