# Generated by Django 5.2.1 on 2026-03-19 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_categoriagasto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cierrediario',
            name='total_gastos_dia',
        ),
    ]
