# Generated by Django 5.2.1 on 2026-03-17 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_integration', '0002_trabajoimpresion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajoimpresion',
            name='creado_por',
        ),
        migrations.AddField(
            model_name='impresora',
            name='imprime_codigo_barras',
            field=models.BooleanField(default=True, help_text='Incluir el código de barras en la etiqueta'),
        ),
        migrations.AddField(
            model_name='impresora',
            name='imprime_nombre',
            field=models.BooleanField(default=True, help_text='Incluir el nombre del producto en la etiqueta'),
        ),
        migrations.AddField(
            model_name='impresora',
            name='imprime_precio',
            field=models.BooleanField(default=True, help_text='Incluir el precio del producto en la etiqueta'),
        ),
        migrations.AddField(
            model_name='trabajoimpresion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_impresion_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plantillaimpresion',
            name='tipo_documento',
            field=models.CharField(choices=[('TICKET', 'Ticket de Venta'), ('FACTURA', 'Factura'), ('ETIQUETA_PRODUCTO', 'Etiqueta de Producto'), ('ETIQUETA_PRECIO', 'Etiqueta de Precio'), ('CODIGO_BARRAS', 'Código de Barras Simple'), ('REPORTE_Z', 'Reporte Z (Cierre de Caja)'), ('VALE', 'Vale/Comprobante')], default='TICKET', max_length=20),
        ),
        migrations.AlterField(
            model_name='registroimpresion',
            name='estado',
            field=models.CharField(choices=[('EXITOSO', '✅ Exitoso'), ('ERROR', '❌ Error'), ('CANCELADO', '⚠️ Cancelado'), ('REINTENTANDO', '🔄 Reintentando')], default='EXITOSO', max_length=20),
        ),
        migrations.AlterField(
            model_name='registroimpresion',
            name='tipo_documento',
            field=models.CharField(choices=[('TICKET', 'Ticket de Venta'), ('FACTURA', 'Factura'), ('ETIQUETA', 'Etiqueta'), ('CODIGO_BARRAS', 'Código de Barras'), ('REPORTE', 'Reporte'), ('OTRO', 'Otro')], default='OTRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='trabajoimpresion',
            name='datos_impresion',
            field=models.TextField(default='', help_text='Contenido a imprimir (comandos ESC/POS, ZPL, etc)'),
        ),
    ]
