# Generated by Django 5.2.1 on 2025-06-09 18:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('taller', '0005_delete_serviciotaller'),
        ('ventas', '0003_alter_detalleventa_servicio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('regla', models.CharField(choices=[('POR_DOLAR', 'Puntos por dólar gastado'), ('POR_VENTA', 'Puntos por venta realizada'), ('POR_REFERIDO', 'Puntos por cliente referido')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Cantidad de puntos o multiplicador', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuración de Puntos',
                'verbose_name_plural': 'Configuraciones de Puntos',
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='moto',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Moto', 'verbose_name_plural': 'Motos'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='descuento_preferencial',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento preferencial en porcentaje', max_digits=5),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='profesion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='puntos_acumulados',
            field=models.PositiveIntegerField(default=0, help_text='Total de puntos acumulados históricamente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='puntos_canjeados',
            field=models.PositiveIntegerField(default=0, help_text='Total de puntos canjeados'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='puntos_disponibles',
            field=models.PositiveIntegerField(default=0, help_text='Puntos disponibles para canjear'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='referido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referidos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='moto',
            name='fecha_ultima_revision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto',
            name='kilometraje',
            field=models.PositiveIntegerField(blank=True, help_text='Kilometraje actual', null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motos', to='clientes.cliente'),
        ),
        migrations.CreateModel(
            name='CanjeoPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_premio', models.CharField(choices=[('DESCUENTO', 'Descuento en compra'), ('SERVICIO_GRATIS', 'Servicio gratuito'), ('PRODUCTO_GRATIS', 'Producto gratuito'), ('OTRO', 'Otro premio')], max_length=20)),
                ('descripcion_premio', models.CharField(max_length=200)),
                ('puntos_utilizados', models.PositiveIntegerField()),
                ('valor_equivalente', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_canje', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('utilizado', models.BooleanField(default=False)),
                ('fecha_utilizacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes', to='clientes.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venta_utilizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canjes_utilizados', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Canje de Puntos',
                'verbose_name_plural': 'Canjes de Puntos',
                'ordering': ['-fecha_canje'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VENTA', 'Venta realizada'), ('SERVICIO', 'Servicio prestado'), ('LLAMADA', 'Llamada telefónica'), ('EMAIL', 'Email enviado'), ('WHATSAPP', 'Mensaje WhatsApp'), ('VISITA', 'Visita al taller'), ('RECLAMO', 'Reclamo o queja'), ('FELICITACION', 'Felicitación'), ('OTRO', 'Otro tipo')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('importante', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='clientes.cliente')),
                ('orden_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller.ordentrabajo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Historial de Cliente',
                'verbose_name_plural': 'Historiales de Clientes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GANADO', 'Puntos Ganados'), ('CANJEADO', 'Puntos Canjeados'), ('AJUSTE', 'Ajuste Manual'), ('VENCIDO', 'Puntos Vencidos')], max_length=20)),
                ('puntos', models.PositiveIntegerField()),
                ('concepto', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_puntos', to='clientes.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Movimiento de Puntos',
                'verbose_name_plural': 'Movimientos de Puntos',
                'ordering': ['-fecha'],
            },
        ),
    ]
