# Generated by Django 5.2.1 on 2026-02-20 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_configuracionpuntos_alter_cliente_options_and_more'),
        ('inventario', '0005_producto_imagen_2_producto_imagen_3_and_more'),
        ('ventas', '0003_alter_detalleventa_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='acepta_marketing',
            field=models.BooleanField(default=False, help_text='Acepta recibir comunicaciones de marketing'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='canal_preferido',
            field=models.CharField(blank=True, choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS')], help_text='Canal preferido de comunicación', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad_envio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_envio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fuente_registro',
            field=models.CharField(blank=True, choices=[('TIENDA', 'Tienda física'), ('WEB', 'Tienda web'), ('REFERIDO', 'Referido'), ('REDES', 'Redes sociales'), ('OTRO', 'Otro')], help_text='Cómo llegó el cliente', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia_envio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='referencia_direccion',
            field=models.CharField(blank=True, help_text='Referencia para encontrar la dirección', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='referencia_envio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número WhatsApp (con código de país, ej: 593999999999)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='descuento_preferencial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='puntos_acumulados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='puntos_canjeados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='puntos_disponibles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='configuracionpuntos',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historialcliente',
            name='tipo',
            field=models.CharField(choices=[('VENTA', 'Venta realizada'), ('PEDIDO_ONLINE', 'Pedido online'), ('SERVICIO', 'Servicio prestado'), ('LLAMADA', 'Llamada telefónica'), ('EMAIL', 'Email enviado'), ('WHATSAPP', 'Mensaje WhatsApp'), ('VISITA', 'Visita al taller'), ('RECLAMO', 'Reclamo o queja'), ('FELICITACION', 'Felicitación'), ('OTRO', 'Otro tipo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='moto',
            name='kilometraje',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PedidoOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(editable=False, max_length=20, unique=True)),
                ('nombres_comprador', models.CharField(max_length=100)),
                ('apellidos_comprador', models.CharField(max_length=100)),
                ('cedula_comprador', models.CharField(max_length=20)),
                ('telefono_comprador', models.CharField(max_length=20)),
                ('email_comprador', models.EmailField(blank=True, max_length=254, null=True)),
                ('tipo_entrega', models.CharField(choices=[('RETIRO', 'Retiro en tienda'), ('SERVIENTREGA', 'Envío por Servientrega')], default='RETIRO', max_length=20)),
                ('direccion_envio', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad_envio', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia_envio', models.CharField(blank=True, max_length=100, null=True)),
                ('referencia_envio', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_guia', models.CharField(blank=True, max_length=50, null=True)),
                ('metodo_pago', models.CharField(choices=[('PAYPHONE', 'Payphone (tarjeta)'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('CONTRA_ENTREGA', 'Pago contra entrega')], max_length=20)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('FALLIDO', 'Fallido'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=20)),
                ('payphone_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payphone_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('comprobante_transferencia', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('banco_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de confirmación'), ('CONFIRMADO', 'Confirmado'), ('PREPARANDO', 'Preparando'), ('DESPACHADO', 'Despachado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_despacho', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_enviado', models.BooleanField(default=False)),
                ('whatsapp_enviado_at', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente registrado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidosonline', to='clientes.cliente')),
                ('venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_online', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Pedido Online',
                'verbose_name_plural': 'Pedidos Online',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200)),
                ('codigo_producto', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen_producto', models.URLField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='clientes.pedidoonline')),
            ],
            options={
                'verbose_name': 'Detalle Pedido Online',
                'verbose_name_plural': 'Detalles Pedidos Online',
            },
        ),
        migrations.AddField(
            model_name='historialcliente',
            name='pedido_online',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.pedidoonline'),
        ),
    ]
