# Generated by Django 5.2.1 on 2026-02-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_acepta_marketing_cliente_canal_preferido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoonline',
            name='comprobante_base64',
            field=models.TextField(blank=True, default='', help_text='Imagen del comprobante codificada en base64 (sin el prefijo data:...)', verbose_name='Comprobante base64'),
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='comprobante_content_type',
            field=models.CharField(blank=True, default='', help_text='Content-type de la imagen base64 (ej: image/jpeg)', max_length=50, verbose_name='Tipo de imagen del comprobante'),
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='numero_comprobante',
            field=models.CharField(blank=True, default='', help_text='Número o código de referencia de la transferencia bancaria', max_length=100, verbose_name='Número de comprobante'),
        ),
        migrations.AlterField(
            model_name='pedidoonline',
            name='banco_origen',
            field=models.CharField(blank=True, help_text='Banco desde donde se realizó la transferencia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoonline',
            name='comprobante_transferencia',
            field=models.ImageField(blank=True, help_text='[Legado] Imagen subida por formulario', null=True, upload_to='comprobantes/'),
        ),
    ]
