# Generated by Django 5.2.1 on 2025-05-16 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taller', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciotaller',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='serviciotaller',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taller.tecnico'),
        ),
        migrations.AddField(
            model_name='serviciotaller',
            name='tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taller.tiposervicio'),
        ),
    ]
