# Generated by Django 5.2.1 on 2025-05-22 13:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0002_alter_producto_options_producto_codigo_barras_and_more'),
        ('taller', '0002_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#007bff', help_text='Color en formato hexadecimal', max_length=7)),
                ('activa', models.BooleanField(default=True)),
                ('requiere_diagnostico', models.BooleanField(default=False)),
                ('tiempo_estimado_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicios',
            },
        ),
        migrations.CreateModel(
            name='EspecialidadTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Especialidad Técnica',
                'verbose_name_plural': 'Especialidades Técnicas',
            },
        ),
        migrations.AlterModelOptions(
            name='tecnico',
            options={'ordering': ['nombres', 'apellidos'], 'verbose_name': 'Técnico', 'verbose_name_plural': 'Técnicos'},
        ),
        migrations.AlterModelOptions(
            name='tiposervicio',
            options={'ordering': ['categoria__nombre', 'nombre'], 'verbose_name': 'Tipo de Servicio', 'verbose_name_plural': 'Tipos de Servicios'},
        ),
        migrations.AddField(
            model_name='tecnico',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='codigo',
            field=models.CharField(default='TEMP', help_text='Código único del técnico', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tecnico',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('VACACIONES', 'En Vacaciones'), ('LICENCIA', 'En Licencia')], default='ACTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='tecnicos/'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='salario_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='nivel_dificultad',
            field=models.CharField(choices=[('BASICO', 'Básico'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado'), ('EXPERTO', 'Experto')], default='BASICO', max_length=20),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='precio_mano_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='requiere_repuestos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='tiempo_estimado_horas',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Tiempo estimado en horas', max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='especialidad',
            field=models.CharField(blank=True, help_text='Especialidad principal (texto libre)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.datetime(2025, 5, 22, 13, 47, 32, 785520, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='porcentaje_comision',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de comisión por servicios', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='tiempo_estimado',
            field=models.IntegerField(blank=True, help_text='Tiempo estimado alternativo (entero)', null=True),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_servicio', to='taller.categoriaservicio'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='especialidades',
            field=models.ManyToManyField(blank=True, to='taller.especialidadtecnica'),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='requiere_especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller.especialidadtecnica'),
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=20, unique=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_prometida', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('motivo_ingreso', models.TextField(help_text='Motivo por el que ingresa la moto')),
                ('diagnostico_inicial', models.TextField(blank=True, null=True)),
                ('diagnostico_final', models.TextField(blank=True, null=True)),
                ('trabajo_realizado', models.TextField(blank=True, null=True)),
                ('observaciones_tecnico', models.TextField(blank=True, null=True)),
                ('observaciones_cliente', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('ESPERANDO_REPUESTOS', 'Esperando Repuestos'), ('ESPERANDO_APROBACION', 'Esperando Aprobación'), ('COMPLETADO', 'Completado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=25)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=20)),
                ('kilometraje_entrada', models.PositiveIntegerField(blank=True, null=True)),
                ('kilometraje_salida', models.PositiveIntegerField(blank=True, null=True)),
                ('nivel_combustible', models.CharField(blank=True, choices=[('VACIO', 'Vacío'), ('1/4', '1/4 de tanque'), ('1/2', '1/2 tanque'), ('3/4', '3/4 de tanque'), ('LLENO', 'Lleno')], max_length=20, null=True)),
                ('precio_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_repuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('facturado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='clientes.cliente')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='clientes.moto')),
                ('tecnico_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_asignadas', to='taller.tecnico')),
                ('tecnicos_apoyo', models.ManyToManyField(blank=True, related_name='ordenes_apoyo', to='taller.tecnico')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_general', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Calificación de 1 a 5')),
                ('calificacion_tecnico', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('calificacion_tiempo', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('calificacion_precio', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('recomendaria', models.BooleanField(default=True)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='taller.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Evaluación de Servicio',
                'verbose_name_plural': 'Evaluaciones de Servicio',
            },
        ),
        migrations.CreateModel(
            name='CitaTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('duracion_estimada', models.PositiveIntegerField(default=60, help_text='Duración estimada en minutos')),
                ('motivo', models.TextField(help_text='Motivo de la cita')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONFIRMADA', 'Confirmada'), ('EN_CURSO', 'En Curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No Asistió')], default='PROGRAMADA', max_length=20)),
                ('recordatorio_enviado', models.BooleanField(default=False)),
                ('fecha_recordatorio', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_taller', to='clientes.cliente')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_taller', to='clientes.moto')),
                ('tecnico_preferido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller.tecnico')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('orden_trabajo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Cita de Taller',
                'verbose_name_plural': 'Citas de Taller',
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado_anterior', models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('ESPERANDO_REPUESTOS', 'Esperando Repuestos'), ('ESPERANDO_APROBACION', 'Esperando Aprobación'), ('COMPLETADO', 'Completado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], max_length=25, null=True)),
                ('estado_nuevo', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('ESPERANDO_REPUESTOS', 'Esperando Repuestos'), ('ESPERANDO_APROBACION', 'Esperando Aprobación'), ('COMPLETADO', 'Completado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], max_length=25)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='taller.ordentrabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento de Orden',
                'verbose_name_plural': 'Seguimientos de Órdenes',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='ServicioOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_mano_obra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_estimado', models.DecimalField(decimal_places=2, help_text='Tiempo estimado en horas', max_digits=5)),
                ('tiempo_real', models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo real empleado', max_digits=5, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('requiere_aprobacion', models.BooleanField(default=False)),
                ('aprobado_cliente', models.BooleanField(default=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='taller.ordentrabajo')),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taller.tecnico')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taller.tiposervicio')),
            ],
            options={
                'verbose_name': 'Servicio de Orden',
                'verbose_name_plural': 'Servicios de Orden',
            },
        ),
        migrations.CreateModel(
            name='RepuestoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_utilizados', to='taller.ordentrabajo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('servicio_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller.servicioorden')),
            ],
            options={
                'verbose_name': 'Repuesto de Orden',
                'verbose_name_plural': 'Repuestos de Orden',
            },
        ),
    ]
