# Generated by Django 5.2.1 on 2025-06-08 20:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('taller', '0003_categoriaservicio_especialidadtecnica_and_more'),
        ('ventas', '0002_detalleventa_es_servicio_detalleventa_tipo_servicio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciotaller',
            name='moto',
        ),
        migrations.RemoveField(
            model_name='serviciotaller',
            name='tecnico',
        ),
        migrations.RemoveField(
            model_name='serviciotaller',
            name='tipo_servicio',
        ),
        migrations.RemoveField(
            model_name='serviciotaller',
            name='venta',
        ),
        migrations.AlterModelOptions(
            name='categoriaservicio',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría de Servicio', 'verbose_name_plural': 'Categorías de Servicios'},
        ),
        migrations.AlterModelOptions(
            name='especialidadtecnica',
            options={'ordering': ['nombre'], 'verbose_name': 'Especialidad Técnica', 'verbose_name_plural': 'Especialidades Técnicas'},
        ),
        migrations.AlterModelOptions(
            name='evaluacionservicio',
            options={'ordering': ['-fecha_evaluacion'], 'verbose_name': 'Evaluación de Servicio', 'verbose_name_plural': 'Evaluaciones de Servicio'},
        ),
        migrations.AlterModelOptions(
            name='repuestoorden',
            options={'ordering': ['producto__nombre'], 'verbose_name': 'Repuesto de Orden', 'verbose_name_plural': 'Repuestos de Orden'},
        ),
        migrations.AlterModelOptions(
            name='servicioorden',
            options={'ordering': ['tipo_servicio__nombre'], 'verbose_name': 'Servicio de Orden', 'verbose_name_plural': 'Servicios de Orden'},
        ),
        migrations.RemoveField(
            model_name='citataller',
            name='moto',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='moto',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='tiposervicio',
            name='tiempo_estimado',
        ),
        migrations.RemoveField(
            model_name='tiposervicio',
            name='unidad_tiempo',
        ),
        migrations.AddField(
            model_name='citataller',
            name='moto_descripcion',
            field=models.CharField(blank=True, help_text='Marca, modelo y placa de la moto', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='moto_año',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='moto_cilindraje',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cilindraje'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='moto_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='moto_marca',
            field=models.CharField(default='', max_length=100, verbose_name='Marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='moto_modelo',
            field=models.CharField(default='', max_length=100, verbose_name='Modelo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='moto_placa',
            field=models.CharField(default='', max_length=20, verbose_name='Placa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repuestoorden',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='repuestoorden',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicioorden',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servicioorden',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='especialidades',
            field=models.ManyToManyField(blank=True, related_name='tecnicos', to='taller.especialidadtecnica'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='tipo_identificacion',
            field=models.CharField(choices=[('CEDULA', 'Cédula'), ('RUC', 'RUC'), ('PASAPORTE', 'Pasaporte')], default='CEDULA', max_length=20),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_servicio', to='taller.categoriaservicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='incluye_iva',
            field=models.BooleanField(default=False, help_text='Los servicios generalmente no incluyen IVA'),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, help_text='Precio base del servicio', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='precio_mano_obra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio adicional por mano de obra', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['numero_orden'], name='taller_orde_numero__2c08a8_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['estado'], name='taller_orde_estado_d47679_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['fecha_ingreso'], name='taller_orde_fecha_i_662c05_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['cliente'], name='taller_orde_cliente_96ea9b_idx'),
        ),
    ]
