# Generated by Django 5.2.1 on 2025-06-08 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0004_remove_serviciotaller_moto_and_more'),
        ('ventas', '0003_alter_detalleventa_servicio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicioTaller',
        ),
    ]
