# Generated by Django 5.2.1 on 2026-01-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0005_delete_serviciotaller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicioorden',
            name='precio_base',
        ),
        migrations.RemoveField(
            model_name='servicioorden',
            name='precio_mano_obra',
        ),
        migrations.RemoveField(
            model_name='servicioorden',
            name='precio_total',
        ),
        migrations.RemoveField(
            model_name='tiposervicio',
            name='incluye_iva',
        ),
        migrations.RemoveField(
            model_name='tiposervicio',
            name='precio_base',
        ),
        migrations.RemoveField(
            model_name='tiposervicio',
            name='precio_mano_obra',
        ),
        migrations.AddField(
            model_name='servicioorden',
            name='precio_servicio',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Precio del servicio en esta orden', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Precio total del servicio (sin IVA)', max_digits=10),
            preserve_default=False,
        ),
    ]
