# Generated by Django 5.2.1 on 2026-03-19 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0006_remove_servicioorden_precio_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioorden',
            name='nombre_servicio_personalizado',
            field=models.CharField(blank=True, help_text='Nombre personalizado para servicios genéricos', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='es_personalizable',
            field=models.BooleanField(default=False, help_text='Si se marca, el nombre y precio serán editables al seleccionar este servicio'),
        ),
        migrations.AlterField(
            model_name='servicioorden',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taller.tiposervicio'),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='nivel_dificultad',
            field=models.CharField(choices=[('BASICO', 'Básico'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado'), ('EXPERTO', 'Experto')], default='BASICO', max_length=200),
        ),
    ]
