# Generated by Django 5.2.1 on 2026-03-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0007_servicioorden_nombre_servicio_personalizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposervicio',
            name='tiempo_estimado_horas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo estimado en horas', max_digits=5, null=True),
        ),
    ]
