# Generated by Django 5.2.1 on 2026-03-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0008_alter_tiposervicio_tiempo_estimado_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
