# Generated by Django 6.0.1 on 2026-04-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0009_tecnico_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuestoorden',
            name='nombre_personalizado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
